### PR TITLE
fix missing players data since recent update

### PR DESCRIPTION
**Pull request by akiver**
Since this CSGO update http://blog.counter-strike.net/index.php/2017/11/19757/ some players were missing.
The table entries loop was stopped prematurely.
I tested on multiple affected demos and it's working now.

### CODE REVIEW

**Comment by moritzuehling** [comment]
Yes, we had the same issue, and the same fix works well in our internal parser, so I can confirm this works. Sadly, we can't just simply backport changes like to this repository due to licensing issues.

About the bug:  
I have no idea why I added that `break;` originally to be honest. I even looked in the blame to check out when this was introduced. Turns out, [the initial commit](https://github.com/StatsHelix/demoinfo/commit/b875e54663cbf5505f96729cb1043496eb1dc733#diff-79c1338de8c0275e43f3937f683df4acR100). Joy.

Lets hope it doesn't break anything, but I don't think it should.

**Comment by akiver** [comment]
Thanks, it's sad that you are not allowed to make important fixes public :/

**Comment by master117** [comment]
> Sadly, we can't just simply backport changes like to this repository due to licensing issues. :/ 

What does that mean? How does this collide with the MIT license?

**Comment by moritzuehling** [comment]
StatsHelix is a company as well. We created demoinfo before we created the company, but now we have our own proprietary code that belongs to the company.

That is the legal side, and the reason why I don't really try to petition to be able to fix bugs here is that I  simply don't have the time as well to fix every bug in this parser. The one we use internally (that I'm maintaining) is quite different and basically a improved version of this.

**Pull request merged**
