### PR TITLE
Check if it's a CSGO demo

### PR DESCRIPTION
**Pull request by Calak**
Must be verified, edited from my smartphone :p

### CODE REVIEW

**Comment by moritzuehling** [comment]
Hey, would be great if someone could quickly test this, as I don't have the setup atm.

**Comment by moritzuehling** [comment]
Sorry for the spam, for us being able to parse the demo this is neccessary, however it's not sufficent - older demos still fail with this. 

Generally the only way to tell if a demo is parsable (even by csgo.exe) is to actually try to parse it, so this really shouldn't be a huge difference in how you handle the parsing.

**Comment by Calak** [comment]
hu? So, what are GameDirectory for older demo?

**Comment by moritzuehling** [comment]
It's the same, but pre-2013 demos don't work with demoinfo, as they don't use GOTV.

**Comment by Calak** [comment]
Thus, this PR stay valid,  no?

**Comment by Calak** [comment]
Demo header still the same for pre-2013 demos  (as cs:s demos),   no?
But what was demo protocol for these old demo? 

Maybe a double-check on demoProtocol/GameDirectory may do the job.

**Comment by main--** [comment]
It's a good idea, but you're kind of on your own there - this is not a priority for us.

If you come up with a better solution - great! If not, we can also just merge this as it's still better than nothing.

**Pull request merged**
